### ISSUE TITLE
Ultimate Ritual 

### ISSUE THREAD

**Issue by ghost** [plaidfluff/ggj2016-music#1]
Ultimate Ritual 

No Team Page

We're doing a pattern repetition game (eg Simon Says). The visual/narrative tone will defiantly be silly, but the music should feel of the occult and charged with a dire energy.

Each successful button sequence brings the player closer to their ultimate goal.  (Lets say there are "5 levels".)  It'd be cool if we got stems to layer in as we progressed and got closer to that goal.
Also, We have five runes(buttons) in the sequencer puzzle, each one has a unique tone that plays. It might be cool to have those tones be relevant to the music.

**Comment by fluffy-critter** [comment]
Sounds like fun. :) So do you want a bunch of separate stems that you'll mix in-game?

**Comment by ghost** [comment]
Yes, that'd be grand.

**Comment by fluffy-critter** [comment]
I'm playing with a few different ideas right now, although this is definitely outside of my comfort zone. :)

There's two ways I could set up the stems:
1. You just start them all playing at the same time and change the mix as the level goes - this is probably easier but it means you can't end one cleanly
2. Every N milliseconds you choose which stems should be playing and start up new one-shot audio players - a bit more difficult to work with but it means that each one can have its own reverb tail and so on

Which way works better for you? Either way is about the same amount of work for me.

**Comment by fluffy-critter** [comment]
oh god dammit Logic crashed on me and I hadn't saved in a while. and of course its auto-recovery save version crashes Logic too. >:(

**Comment by fluffy-critter** [comment]
Okay I have some music up. http://ggj.metronomic.tk

I'll work on sound effects later :)

**Comment by ghost** [comment]
Man, this is amazing. Couldn't have asked for anything better.

**Comment by fluffy-critter** [comment]
Better was the version that got lost in the crash. :)

**Comment by fluffy-critter** [comment]
I also added some button sounds earlier. Dunno if they're quite what you wanted though.

**Comment by ghost** [comment]
I'll check em out

**Comment by fluffy-critter** [comment]
Need anything else? Also, don't forget to add me to the team page when you get it set up. :)

**Comment by fluffy-critter** [comment]
I've tweaked the EQ on the chorus stem to make it stand out a bit more in the mix (and also updated the full mix in case you want to hear how it should all fit together).

**Comment by ghost** [comment]
What are you registered in

**Comment by fluffy-critter** [comment]
What do you mean?

**Comment by ghost** [comment]
How do we find your name to add it to our team

**Comment by fluffy-critter** [comment]
My username is 'fluffy'. http://globalgamejam.org/users/fluffy
