### ISSUE TITLE
Ritualistic Roommates

### ISSUE THREAD

**Issue by chunwyu-2** [plaidfluff/ggj2016-music#2]
This is a game about being the landlord of an apartment. Every tenant is adamant about their particularities and rituals, and when they're overly stressed about these obsessions not being fulfilled (e.g. neat freak seeing a mess, guy sees toilet paper roll facing in instead of out) they would go on a tantrum, break a bunch of things, and then leave. The tenant is then immediately replaced and your apartment rating drops a star.

Given an environment predisposed to chaos, I'd like a touch of irony with some very homely music. Almost to corporate muzak territory. This is a wonderful 3.5br/8ba to live in, after all.

**Comment by fluffy-critter** [comment]
Haha, I had some ideas during your pitch. Let's see if I can do any of them. :)

**Comment by fluffy-critter** [comment]
I just put a crappy thrown-together bossa thing at http://ggj.metronomic.tk/

**Comment by fluffy-critter** [comment]
and also 'snarkosaurus' which is probably not at all what you were hoping for :)

**Comment by chunwyu-2** [comment]
snarkosaurus sounds a little too electronic for my taste. Bossa Move definitely works in the game loop though! Thanks!

Maybe a vaporwave/elevator music thing would fit the menu screen. Like you're sitting in a leasing office not knowing what you're getting into.

**Comment by fluffy-critter** [comment]
Yeah snarkosaurus is just something I thought would be silly. I'll move it to the general folder if you don't want it.

A vaporwave Muzak thing sounds like fun. I'll see what I can do.

**Comment by fluffy-critter** [comment]
I just added "in the lobby."

**Comment by fluffy-critter** [comment]
and I just improved the mix, probably

**Comment by fluffy-critter** [comment]
Need anything else? Also, don't forget to add me to the team page when you get it set up. :)

**Comment by chunwyu-2** [comment]
Thanks for the new track! Could you soften "in the lobby" a bunch? I like the melody but I could see the beat track and the highs crowding out sound effects.

Speaking of which, we probably want some sound effects:
- Cartoonish angry grumbling
- Sad tuba
- Locking and unlocking door
- Opening and closing door
- Toilet seat up and down
- A/C hum

And yes, you're totally going on the team page once I figure out how to make one. :)

**Comment by fluffy-critter** [comment]
Okay, I'm changing the mix a bit right now. and I'll get on the sound effects.

**Comment by fluffy-critter** [comment]
I've done a first pass at the sound effects. It's convenient that there's a bathroom and a locking door within 30 feet of my studio computer. :)

**Comment by chunwyu-2** [comment]
I mean there's one that close to me here too, it only happens to be weird to bring a mic into it.

**Comment by chunwyu-2** [comment]
Just listened to them. May I have versions without the synth tunes (that first 1s or so) for the SFX (like the toilet seat and door)? I prefer just the raw sound for those. :)

I like the synth tune for the toilet-down separately though, that's a good "oops" sound alongside the stronger sad tuba.

Angry Grumble is excellent.

**Comment by fluffy-critter** [comment]
Sure, I'll get right on that. :) Also I purposefully degraded the recordings to sound like 8-bit video game sounds but I can turn that off.

**Comment by chunwyu-2** [comment]
The recording itself is great, I just prefer it without the synth. :)

**Comment by fluffy-critter** [comment]
Okay, I uploaded both clean and bitcrushed versions of things on their own.

**Comment by fluffy-critter** [comment]
I also went ahead and added some one-shot noises for when the AC starts and stops, rather than just the ongoing hum. Use them or don't. :)

**Comment by chunwyu-2** [comment]
Everything is awesome. I'm rigging the sounds up now.

The AC itself might not make it in the game in time, sorry. :(
We'll open that to the public in case anyone wants to use it.

What might, though, is making the bed. Maybe. The two states are: blankets covering the whole bed and blankets rolled up at the foot of the bed.

**Comment by fluffy-critter** [comment]
Are you saying you need sounds for that?

**Comment by chunwyu-2** [comment]
Yeah, in the following order of priority:
1) Light switch on/off
2) Smoothing "in the lobby"
3) Make bed up/down

Sorry for being difficult. I should have made a list from the beginning.

**Comment by fluffy-critter** [comment]
I thought I'd already done 2. Is there something else you'd like changed in it?

**Comment by fluffy-critter** [comment]
I just realized my kitchen vent would have made a great AC hum noise, instead of doing weird stuff with synthesizers. Oh well!

**Comment by fluffy-critter** [comment]
Okay just added crappy light switch and bed making/unmaking sounds.

**Comment by chunwyu-2** [comment]
Re #2: Ah, should have listened to it before asking. It's better but still sounds a little loud/harsh. Probably can't be an in-game BGM, but would work in the main menu if we manage to make one.

Bed-making is good. Is it just me or does light switch off have a long silence in the beginning?

**Comment by fluffy-critter** [comment]
Oops, I messed up while bouncing the light and bed sounds. Fixed.

Also changed the In The Lobby mix a little, mostly to soften up the drums.

**Comment by chunwyu-2** [comment]
New lights sounds are wonderful and hooked in. In the Lobby fits much better now, going to work on Main Menu ASAP.

Thanks a lot!
