### ISSUE TITLE
Er: R0R

### ISSUE THREAD

**Issue by sophiabaldonado** [plaidfluff/ggj2016-music#3]
Hi! I know it's late but if you do have time we'd love some custom sounds/music.
1. The name of your game
   Er: R0R
2. A link to the game's team page
   http://globalgamejam.org/2016/games/err0r
3. A brief description of the game and what sort of music you want (if you have a specific thing in mind)
   Premise: Exploration game disguised as platformer. The more you try to break the game, the closer you get to beating it.
   Certain, seemingly random, sequences of actions will award access codes. These codes can be used to access locked areas of the level that are more fun, challenging, and rewarding.
   Set in an industrial factory, you play as a dysfunctional robot, R0R. Environment includes barrels, crates, saw blades, spikes, and security (enemy) bots.
   A music track would be nice, maybe looping? Also any industrial, machine, robot sound effects would be great.
4. Any special requests (file format, separate layers for interactive mix, etc.)
   prefer .ogg but not required

Thanks!
![robot_idle](https://cloud.githubusercontent.com/assets/1866001/12700691/f312c138-c7a1-11e5-80c9-be269706c038.png)

**Comment by fluffy-critter** [comment]
Ooh, sounds like fun. I'll try to work on some things.

**Comment by sophiabaldonado** [comment]
Wonderful!

**Comment by fluffy-critter** [comment]
Okay I whipped up a gameplay music. I'll probably want to change the EQ to accommodate game sounds though. They're up at http://ggj.metronomic.tk/

**Comment by fluffy-critter** [comment]
I uploaded some basic robot talking sounds. Trying to figure out what I want to do for background mechanical sounds right now. You might consider checking out freesound.org for sound effects though. I don't have a machine shop or foley room in my home studio. :)

**Comment by fluffy-critter** [comment]
And now some buzzes and charangs. :)

**Comment by sophiabaldonado** [comment]
Awesome, thanks so much! I'll definitely check out freesound as well, but I think we'll make good use of some of these sounds.

**Comment by fluffy-critter** [comment]
No problem! If no other projects come in tomorrow I might durdle away at sounds for this some more because I really like the idea.

Also, remember to add me (and your other collaborators!) to your game page. :)

**Comment by fluffy-critter** [comment]
I'm guessing it's probably too late but I just uploaded a bunch of bang sound effects as well. :)

**Comment by fluffy-critter** [comment]
Is it possible to add me to your team? I'd like this game to show up on my GGJ profile. Thanks! :)

**Comment by sophiabaldonado** [comment]
Sure! We're still working on getting the music in game lol
